import Account from './account.svg'
import EyecamCo from './eyecam-co.svg'
import Faceit from './faceit.svg'
import Insure from './insure.svg'
import Manage from './manage.svg'
import MyHome from './myhome.svg'
import Photosnap from './photosnap.svg'
import Shortly from './shortly.svg'
import TheAirFilterCompany from './the-air-filter-company.svg'
import LoopStudio from './loop-studios.svg'
export { Account, Faceit, Insure, Manage, MyHome, Photosnap, EyecamCo, Shortly, TheAirFilterCompany, LoopStudio }